parameters:
#    anmol_hello.example.class: Anmol\HelloBundle\Example

services:
#    anmol_hello.example:
#        class: %anmol_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
